### ISSUE TITLE
Validating css

### ISSUE THREAD

**Issue by baktrius** [baktrius/awww-tester#1]
Wykonanie walidacji plików css z użyciem jakiegoś z podanych w treści narzędzi. (raczej proste)

**Comment by NanoUser3000** [comment]
Jest pull request: #6 

W razie czego można będzie to dostosowywać wg potrzeb, ale jest dosyć solidnie zrobione.

W miarę przetestowane - nie wiadomo tylko jakie warningi może dawać W3C i jakie nadaje im rangi.
